/* File generated by ygs tool on 28/08/2022 at 05:26:15PM, do not manually modify. */
///////////////////////////////////////////////////////////////////////
// Editor.ygs.h
//
//  Copyright 08/28/2022 Edgar Glowacki.
//
//  Maintained by: Edgar
//
//  NOTES:
//      file_notes_go_here
//
//
//  #include "Editor.ygs.h"
//
//////////////////////////////////////////////////////////////////////
//! \file
#pragma once

#include "YagetCore.h"
