/* File generated by ygs tool on 07/07/2022 at 10:56:04PM, do not manually modify. */
///////////////////////////////////////////////////////////////////////
// Editor.ygs.h
//
//  Copyright 07/07/2022 Edgar Glowacki.
//
//  Maintained by: Edgar
//
//  NOTES:
//      file_notes_go_here
//
//
//  #include "Editor.ygs.h"
//
//////////////////////////////////////////////////////////////////////
//! \file
#pragma once

#include "YagetCore.h"
